imports:
    - { resource: 'fixtures/shop_configuration.yaml' }
    - { resource: 'fixtures/graine.yaml' }
    - { resource: 'fixtures/chocolat.yaml' }
    - { resource: 'fixtures/huile.yaml' }

parameters:
    env(SYLIUS_FIXTURES_HOSTNAME): 'localhost'
    env(SYLIUS_FIXTURES_THEME_NAME): 'sylius/bootstrap-theme'
