imports:
    - { resource: 'fixtures/shop_configuration.yaml' }
    - { resource: 'fixtures/graine.yaml' }

parameters:
    env(SYLIUS_FIXTURES_HOSTNAME): 'localhost'
    env(SYLIUS_FIXTURES_THEME_NAME): ~
