sylius_fixtures:
    suites:
        lchanvre:
            listeners:
                orm_purger: ~
                logger: ~

            fixtures:
                locale: ~
                currency:
                    options:
                        currencies: ['EUR']

                geographical:
                    options:
                        countries:
                            - 'FR'
                        zones:
                            FR:
                                name: 'France'
                                countries:
                                    - 'FR'

                taxon:
                    options:
                        custom:
                            products:
                                code: 'produits'
                                name: "Produits"
                                slug: 'produits'

                channel:
                    options:
                        custom:
                            fashion_web_store:
                                name: 'LChanvre'
                                code: 'lchanvre'
                                locales:
                                    - '%locale%'
                                currencies:
                                    - 'EUR'
                                enabled: true
                                hostname: 'lchanvre.wip'
                
                payment_method:
                    options:
                        custom:
                            bank_card:
                                code: bank_card
                                name: 'Carte bleu'
                                channels: [lchanvre]
                                gatewayName: 'system_pay_bank_card'
                                gatewayFactory: 'system_pay'
                                gatewayConfig:
                                    payum.http_client: '@waaz.system_pay.bridge.system_pay_bridge'
                                    environment: '%system_pay_environment%'
                                    secret_key: '%system_pay_secret_key%'
                                    merchant_id: '%system_pay_merchant_id%'
                                    payment_cards: 'VISA;MASTERCARD'
                                    use_old_security: true

                customer_group:
                    options:
                        custom:
                            retail:
                                code: "retail"
                                name: "Retail"

                shop_user:
                    name: "shop_user"
                    options:
                        random: 2
                        custom:
                            -   email: "shop@example.com"
                                first_name: "John"
                                last_name: "Doe"
                                password: "sylius"
                            -   email: "custom@example.com"
                                first_name: "Marek"
                                last_name: "Markowski"
                                password: "sylius"

                admin_user:
                    name: "admin_user"
                    options:
                        custom:
                            -   email: "admin@lchanvre.com"
                                username: "admin"
                                password: "root"
                                enabled: true
                                locale_code: fr_FR
                                first_name: Admin
                                last_name: LChanvre

                tax_category:
                    options:
                        custom:
                            clothing:
                                code: "food"
                                name: "Nourriture"

                tax_rate:
                    options:
                        custom:
                            clothing_tax:
                                code: "food_55"
                                name: "TVA 5.5%"
                                zone: "FR"
                                category: "food"
                                amount: 0.055
